title: Zoreslav Khimich
email: me@zoreslav.com
description: >-
  Hey, I'm Zoreslav. I build mobile apps for Apple devices. Here are the details.

baseurl: ""
url: "" 
github_username: zrxq
linkedin_username: zoreslav
